import type { Icon } from "@phosphor-icons/react";
import {
  Bed,
  SwimmingPool,
  CookingPot,
  Waves,
  LetterCircleP,
  CigaretteSlash,
  PawPrint,
  ThermometerHot,
  Snowflake,
  WifiHigh,
  BellSimpleRinging,
  Bathtub,
  Feather,
  Vault,
  BeachBall,
  Bread,
  Package,       // fridge (Fridge not in Phosphor)
  Coffee,
  Television,
  MoonStars,
  SpeakerSlash,
  Towel,         // hand-towel (HandTowel not in Phosphor)
  Broom,
  HandSoap,
  Buildings,
  UsersThree,
  Baby,
  Chair,
  Wheelchair,
  WashingMachine,
  Barbell,       // dumbbell (Dumbbell not in Phosphor)
  Flower,        // spa (Spa not in Phosphor)
  Fire,
  HairDryer,
  CoatHanger,
  Desk,
  Usb,
  SuitcaseRolling,
  TShirt,
  Footprints,
  PhoneCall,
  Suitcase,
  CarProfile,
  AirplaneTakeoff,
  Thermometer,
  Sun,
  ForkKnife,
  Cookie,
  Drop,          // drops (Drops not in Phosphor)
  BellSlash,
  Lock,
  IdentificationBadge,
  HandHeart,
  Translate,
  Bicycle,
  Archive,       // archive-box (ArchiveBox not in Phosphor)
  MapTrifold,
  ClockCounterClockwise,
  ClockClockwise,
  ArrowFatLinesUp,
  Gift,
  Leaf,
  Monitor,
  Presentation,
  Briefcase,
  Garage,
  Wine,          // also fallback for cocktail
  Keyhole,
  CircleDashed,  // pillows + fallback
  DiceFive,
  PuzzlePiece,
  Compass,
  Camera,
  CarSimple,
  SealCheck,
  Tag,
  Car,
  House,
  Wind,
} from "@phosphor-icons/react";

const ICON_MAP: Record<string, Icon> = {
  "bed":                     Bed,
  "swimming-pool":           SwimmingPool,
  "cooking-pot":             CookingPot,
  "waves":                   Waves,
  "letter-circle-p":         LetterCircleP,
  "cigarette-slash":         CigaretteSlash,
  "paw-print":               PawPrint,
  "thermometer-hot":         ThermometerHot,
  "snowflake":               Snowflake,
  "wifi-high":               WifiHigh,
  "bell-simple-ringing":     BellSimpleRinging,
  "bathtub":                 Bathtub,
  "feather":                 Feather,
  "vault":                   Vault,
  "beach-ball":              BeachBall,
  "bread":                   Bread,
  "fridge":                  Package,
  "coffee":                  Coffee,
  "television":              Television,
  "moon-stars":              MoonStars,
  "speaker-slash":           SpeakerSlash,
  "hand-towel":              Towel,
  "broom":                   Broom,
  "hand-soap":               HandSoap,
  "buildings":               Buildings,
  "users-three":             UsersThree,
  "baby":                    Baby,
  "chair":                   Chair,
  "wheelchair":              Wheelchair,
  "washing-machine":         WashingMachine,
  "dumbbell":                Barbell,
  "spa":                     Flower,
  "fire":                    Fire,
  "hair-dryer":              HairDryer,
  "coat-hanger":             CoatHanger,
  "desk":                    Desk,
  "usb":                     Usb,
  "suitcase-rolling":        SuitcaseRolling,
  "t-shirt":                 TShirt,
  "footprints":              Footprints,
  "phone-call":              PhoneCall,
  "suitcase":                Suitcase,
  "car-profile":             CarProfile,
  "airplane-takeoff":        AirplaneTakeoff,
  "thermometer":             Thermometer,
  "sun":                     Sun,
  "fork-knife":              ForkKnife,
  "restaurant":              ForkKnife,
  "cookie":                  Cookie,
  "drops":                   Drop,
  "bell-slash":              BellSlash,
  "lock":                    Lock,
  "identification-badge":    IdentificationBadge,
  "hand-heart":              HandHeart,
  "translate":               Translate,
  "bicycle":                 Bicycle,
  "archive-box":             Archive,
  "map-trifold":             MapTrifold,
  "clock-counter-clockwise": ClockCounterClockwise,
  "clock-clockwise":         ClockClockwise,
  "arrow-fat-lines-up":      ArrowFatLinesUp,
  "gift":                    Gift,
  "leaf":                    Leaf,
  "monitor":                 Monitor,
  "presentation":            Presentation,
  "briefcase":               Briefcase,
  "garage":                  Garage,
  "cocktail":                Wine,
  "wine":                    Wine,
  "keyhole":                 Keyhole,
  "pillows":                 CircleDashed,
  "dice-five":               DiceFive,
  "puzzle-piece":            PuzzlePiece,
  "compass":                 Compass,
  "camera":                  Camera,
  "car-simple":              CarSimple,
  "seal-check":              SealCheck,
  "circle-dashed":           CircleDashed,
  // Legacy Lucide icon name aliases (for backwards-compatibility with old seed data)
  "tag":                     Tag,
  "car":                     Car,
  "home":                    House,
  "wind":                    Wind,
  "utensils":                ForkKnife,
  "wifi":                    WifiHigh,
  "tv":                      Television,
};

export function AmenityChip({ icon, name }: { icon: string; name: string }) {
  const IconComponent = ICON_MAP[icon] ?? CircleDashed;
  return (
    <span className="inline-flex items-center gap-1 text-xs text-stone-500">
      <IconComponent size={14} weight="regular" />
      {name}
    </span>
  );
}
